### ISSUE TITLE
Create contact profile page 

### ISSUE THREAD

**Issue by mdshamoon** [glific/mobile#68]
**Is your feature request related to a problem? Please describe.**
After reading the messages of a contact I want to check the various details of the contact. For that we need a contact profile page

**Describe the solution you'd like**

- Create a static contact profile page according to the designs: 
- This page would open when we click on the contacts name in the messages section similar to how we have on WhatsApp

<img width="266" alt="image" src="https://github.com/glific/mobile/assets/32592458/1f85be6d-3bdc-4264-a0ff-19aa9e1d5dbe">

Design file link: https://www.figma.com/file/SbP0ru8kiB2l334ieX1ESe/Mobile-app?type=design&node-id=372-3254&t=Ioc2SXIPBBrgS7Im-0

**Comment by mdshamoon** [comment]
@ANEESH-2003 you can work on this issue. Let Aman work on the side drawer

**Comment by ANEESH-2003** [comment]
sure sir

**Comment by Siva20021** [comment]
is Contact Profile Page already done ?

**Comment by mdshamoon** [comment]
Hi @ANEESH-2003 please let me know  if you are working on it. If not please let @Siva20021 know and he can take it forward

**Comment by Siva20021** [comment]
Is there any other page where I can work still which is pending ? 

I am new to opensource as well .

**Comment by ANEESH-2003** [comment]
Hi @mdshamoon sir i am working on it.

**Comment by chandra-pro** [comment]
@mdshamoon is anyone working on this issue?

**Comment by ANEESH-2003** [comment]
hi @mdshamoon sir i have some doubts: 
1) can you tell me how to access all these information as currently i am able to access id, lastmessageat, name.
2) what do you want "view more" option in contact history to do (a) open another page with full list of contact history, (b) give some more rows in the current page.

MY PROGRESS till now :
(1) i have created new screeen which opens up everytime you click a contact name in chat just like whatsapp.
(2) design is same as design file given but cannot show the contact specific info due to the reasons stated above.

**Comment by mdshamoon** [comment]
Hey how's it going @ANEESH-2003

**Comment by mdshamoon** [comment]
This is completed. Closing
